from typing import Protocol

class AbstractQueryDAO(Protocol):
    """Structural interface for analytical query interactions."""
    def start_execution(self, query: str, database: str, output: str) -> str: ...
    def fetch_execution_state(self, query_id: str) -> str: ...

class AbstractAthenaAnalyticsService(Protocol):
    """Structural interface for Athena-specific analytical operations."""
    def run_query(self, query: str, database: str, output: str) -> str: ...
    def wait_completion(self, query_id: str) -> str: ...
