from typing import Protocol

class AbstractMetadataDAO(Protocol):
    """Structural interface for metadata discovery interactions."""
    def trigger_crawler(self, name: str) -> None: ...
    def fetch_crawler_state(self, name: str) -> str: ...

class AbstractGlueDiscoveryService(Protocol):
    """Structural interface for Glue-specific discovery operations."""
    def refresh(self) -> None: ...
    def wait_ready(self) -> str: ...
